PORTFOLIOS: dict[str, list[str]] = {
    'Mayra': [
        'Heineken Brasil',
        'Mercado Livre',
        'Embraer',
        'Ternium',
        'Usiminas',
        'Gerdau',
        'Natura & Co',
        'Prologis',
        'Tenaris',
    ],
    'Adriana': [
        'BAT Brasil',
        'LATAM Airlines',
        'BASF Brasil',
        'Mosaic Fertilizantes',
        'Grupo Bimbo',
        'Minerva Foods',
        'John Deere Brasil',
        'CMPC',
        'Bayer Brasil',
        'Amcor',
    ],
    'Renata': [
        'Amazon Brasil',
        'GLP Brasil',
        'Tupy',
        'Shopee Brasil',
        'Electrolux Brasil',
        'Ball Corporation',
        'JTI Brasil',
        'Whirlpool Brasil',
        'Klabin',
        'Grupo Boticário',
    ],
    'Rogério': [
        'Raízen',
        'Braskem',
        'Vale',
        'Hydro Brasil',
    ],
}
